services:
  - type: web
    name: kakumei-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python proxy.py
    region: oregon
    plan: free
    runtime: python
